



TESTS_TESTING = False
TESTS_ONLY_MEGAGROUPS = True

TESTS_SHOW_BOT_SETTINGS = False
UI_SWITCH_PAGES = True

TELETHON_REQUEST_HASH = 0
TELETHON_REQUEST_LASTDATE = None
TELETHON_REQUEST_CHUNKSIZE = 200
TELETHON_REQUEST_OFFSETID = 0

