

APP_TITLE = "David's Telebot by rt-2"

TESTS_TESTING = False
TESTS_ONLY_MEGAGROUPS = True

UI_SWITCH_PAGES = True


TELETHON_REQUEST_HASH = 0
TELETHON_REQUEST_LASTDATE = None
TELETHON_REQUEST_CHUNKSIZE = 200
TELETHON_REQUEST_OFFSETID = 0

ADDTIME_RANDOM = 60
ADDTIME_EACH = 90
ADDTIME_WAIT = 100
